// <auto-generated />
using System;
using Kelly.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kelly.Migrations
{
    [DbContext(typeof(KellyDbContext))]
    [Migration("20260713222604_SU2")]
    partial class SU2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kelly.Models.Entities.AboutFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AboutFacts");
                });

            modelBuilder.Entity("Kelly.Models.Entities.AboutPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("AboutAge")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly?>("AboutBirthday")
                        .HasColumnType("date");

                    b.Property<string>("AboutCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AboutFreelance")
                        .HasColumnType("bit");

                    b.Property<string>("AboutPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactsUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillsUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestimonialsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestimonialsUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutPages");
                });

            modelBuilder.Entity("Kelly.Models.Entities.AboutSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AboutSkills");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("SendDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YourName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ContactPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Card1Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card1IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card1Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card2IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card2Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card3Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card3IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card3Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormButtonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactPages");
                });

            modelBuilder.Entity("Kelly.Models.Entities.HomePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageButtonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomePages");
                });

            modelBuilder.Entity("Kelly.Models.Entities.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EditorContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PortfolioPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ProjectDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioPageId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("Kelly.Models.Entities.PortfolioItemImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PortfolioItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioItemId");

                    b.ToTable("PortfolioItemImages");
                });

            modelBuilder.Entity("Kelly.Models.Entities.PortfolioPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioPages");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ResumeEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndYear")
                        .HasColumnType("date");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ResumePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartYear")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumePageId");

                    b.ToTable("ResumeEducations");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ResumeExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndYear")
                        .HasColumnType("date");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ResumePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartYear")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumePageId");

                    b.ToTable("ResumeExperiences");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ResumePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResumePages");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ResumeSumary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ResumePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumePageId");

                    b.ToTable("ResumeSumaries");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ServiceCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ServicePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServicePageId");

                    b.ToTable("ServiceCards");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ServicePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServicePages");
                });

            modelBuilder.Entity("Kelly.Models.Entities.SiteSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CopyTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("Kelly.Models.Entities.Testimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("Kelly.Models.Entities.PortfolioItem", b =>
                {
                    b.HasOne("Kelly.Models.Entities.PortfolioPage", "PortfolioPage")
                        .WithMany("Items")
                        .HasForeignKey("PortfolioPageId");

                    b.Navigation("PortfolioPage");
                });

            modelBuilder.Entity("Kelly.Models.Entities.PortfolioItemImage", b =>
                {
                    b.HasOne("Kelly.Models.Entities.PortfolioItem", "Item")
                        .WithMany("Images")
                        .HasForeignKey("PortfolioItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ResumeEducation", b =>
                {
                    b.HasOne("Kelly.Models.Entities.ResumePage", "ResumePage")
                        .WithMany("Educations")
                        .HasForeignKey("ResumePageId");

                    b.Navigation("ResumePage");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ResumeExperience", b =>
                {
                    b.HasOne("Kelly.Models.Entities.ResumePage", "ResumePage")
                        .WithMany("Experiences")
                        .HasForeignKey("ResumePageId");

                    b.Navigation("ResumePage");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ResumeSumary", b =>
                {
                    b.HasOne("Kelly.Models.Entities.ResumePage", "ResumePage")
                        .WithMany("Sumary")
                        .HasForeignKey("ResumePageId");

                    b.Navigation("ResumePage");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ServiceCard", b =>
                {
                    b.HasOne("Kelly.Models.Entities.ServicePage", "ServicePage")
                        .WithMany("ServiceCards")
                        .HasForeignKey("ServicePageId");

                    b.Navigation("ServicePage");
                });

            modelBuilder.Entity("Kelly.Models.Entities.PortfolioItem", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Kelly.Models.Entities.PortfolioPage", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ResumePage", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Sumary");
                });

            modelBuilder.Entity("Kelly.Models.Entities.ServicePage", b =>
                {
                    b.Navigation("ServiceCards");
                });
#pragma warning restore 612, 618
        }
    }
}
